// ==================================================================
// Build script — compiles Node.js automation modules into a single
// browser-compatible bundle for the Chrome extension
// Run: node extension/build.js
// ==================================================================
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const AUTO = path.join(ROOT, 'automation');
const OUT = path.join(__dirname, 'shared', 'automation-bundle.js');

// Modules to inline (order matters — dependencies first)
const modules = [
    // Helpers
    { name: 'sleep', src: null, inline: `function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }` },
    { name: 'postback', src: path.join(AUTO, 'helpers', 'postback.js') },
    { name: 'fill-field', src: path.join(AUTO, 'helpers', 'fill-field.js') },
    { name: 'add-another', src: path.join(AUTO, 'helpers', 'add-another.js') },
    { name: 'verify', src: path.join(AUTO, 'helpers', 'verify.js') },
    // Field maps
    { name: 'field-maps-shared', src: path.join(AUTO, 'field-maps', 'shared.js') },
    { name: 'b1-b2-modular', src: path.join(AUTO, 'field-maps', 'b1-b2-modular.js') },
    // Pages
    { name: 'generic-page', src: path.join(AUTO, 'pages', 'generic-page.js') },
    { name: 'travel-page', src: path.join(AUTO, 'pages', 'travel-page.js') },
    // Specialized pages (F/J/O)
    { name: 'student-exchange-map', src: findPageFieldMap('18-student-exchange'), optional: true },
    { name: 'petition-info-map', src: findPageFieldMap('19-petition-info'), optional: true },
    { name: 'student-add-contact-map', src: findPageFieldMap('19a-student-add-contact'), optional: true },
    // Field map router
    { name: 'field-maps-index', src: path.join(AUTO, 'field-maps', 'index.js') },
    // normalizeProfile from filler.js
    { name: 'normalize', src: null, extract: true },
];

function findPageFieldMap(pageName) {
    const p = path.join(AUTO, 'pages', pageName, 'field-map.js');
    return fs.existsSync(p) ? p : null;
}

/**
 * Convert a Node.js module to browser-compatible code:
 * - Replace require('./...') with window references
 * - Replace module.exports with window assignments
 */
function convertToBrowser(code, name) {
    // Remove 'use strict' (we'll add it globally)
    code = code.replace(/['"]use strict['"];?\s*/g, '');

    // Replace require statements with window references
    code = code.replace(/const\s+\{([^}]+)\}\s*=\s*require\([^)]+\);?/g, (match, imports) => {
        // These are already available as globals from prior modules
        return `// [bundle] ${imports.trim()} — available from prior modules`;
    });
    code = code.replace(/const\s+(\w+)\s*=\s*require\([^)]+\);?/g, (match, varName) => {
        return `// [bundle] ${varName} — available from prior modules`;
    });
    code = code.replace(/require\([^)]+\)/g, '{}');

    // Replace module.exports
    code = code.replace(/module\.exports\s*=\s*\{([^}]+)\}/g, (match, exports) => {
        const items = exports.split(',').map(e => e.trim().split(':')[0].trim()).filter(Boolean);
        return `// Exported: ${items.join(', ')}`;
    });
    code = code.replace(/module\.exports\s*=\s*require\([^)]+\);?/g, '');

    return code;
}

/**
 * Extract normalizeProfile and identifyPage from filler.js
 */
function extractFromFiller() {
    const fillerSrc = fs.readFileSync(path.join(AUTO, 'filler.js'), 'utf-8');
    
    // Extract normalizeProfile function
    const normalizeMatch = fillerSrc.match(/function normalizeProfile\([\s\S]*?\n\}/m);
    
    // Extract identifyPage function
    const identifyMatch = fillerSrc.match(/function identifyPage\([\s\S]*?\n\}/m);
    
    // Extract isFinalPage function
    const finalMatch = fillerSrc.match(/function isFinalPage\([\s\S]*?\n\}/m);

    let result = '';
    if (normalizeMatch) result += normalizeMatch[0] + '\n\n';
    if (identifyMatch) result += identifyMatch[0] + '\n\n';
    if (finalMatch) result += finalMatch[0] + '\n\n';
    
    return result;
}

// ============================================================
// BUILD
// ============================================================
console.log('🔨 Building automation bundle for extension...\n');

let bundle = `// ==================================================================
// AUTOMATION BUNDLE — auto-generated by extension/build.js
// Contains all DS-160 automation logic for content scripts
// Generated: ${new Date().toISOString()}
// DO NOT EDIT — edit source files and re-run build
// ==================================================================
'use strict';

`;

// Add each module
for (const mod of modules) {
    if (mod.optional && !mod.src) {
        console.log(`  ⏭ ${mod.name} (optional, not found)`);
        continue;
    }
    if (mod.inline) {
        bundle += `\n// === ${mod.name} ===\n${mod.inline}\n`;
        console.log(`  ✅ ${mod.name} (inline)`);
        continue;
    }
    if (mod.extract) {
        const extracted = extractFromFiller();
        if (extracted) {
            bundle += `\n// === Functions extracted from filler.js ===\n${extracted}\n`;
            console.log(`  ✅ normalize/identifyPage/isFinalPage (extracted from filler.js)`);
        }
        continue;
    }
    
    try {
        const raw = fs.readFileSync(mod.src, 'utf-8');
        const converted = convertToBrowser(raw, mod.name);
        bundle += `\n// === ${mod.name} (${path.basename(mod.src)}) ===\n${converted}\n`;
        console.log(`  ✅ ${mod.name} (${path.basename(mod.src)})`);
    } catch (err) {
        console.warn(`  ⚠️ ${mod.name}: ${err.message}`);
    }
}

// Make key functions available globally
bundle += `
// === Global exports for content scripts ===
window._automation = {
    buildDynamicFieldMap,
    isPostbackSelect,
    isPostbackClick,
    fillPage,
    verifyPage,
    normalizeProfile,
    identifyPage,
    isFinalPage,
    waitForPostback,
    waitForPageReady,
    waitForUrlChange,
    discoverFields,
    fillText,
    fillTextBatch,
    fillSelect,
    fillRadio,
    fillCheckbox,
    isSelectEmpty,
    getValidationErrors,
    sleep,
};
`;

fs.writeFileSync(OUT, bundle, 'utf-8');
const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`\n📦 Bundle written: ${OUT} (${sizeKB} KB)`);
