/**
 * DS-160 Shared Options — Listas reutilizáveis across sections
 * Extraído de ds160-schema.js para modularização
 */
export const countries = [
    { value: "BRZL", label: "BRAZIL" },
    { value: "AFGH", label: "AFGHANISTAN" },
    { value: "ALB", label: "ALBANIA" },
    { value: "ALGR", label: "ALGERIA" },
    { value: "ANDO", label: "ANDORRA" },
    { value: "ANGL", label: "ANGOLA" },
    { value: "ANGU", label: "ANGUILLA" },
    { value: "ANTI", label: "ANTIGUA AND BARBUDA" },
    { value: "ARG", label: "ARGENTINA" },
    { value: "ARM", label: "ARMENIA" },
    { value: "ASTL", label: "AUSTRALIA" },
    { value: "AUST", label: "AUSTRIA" },
    { value: "AZR", label: "AZERBAIJAN" },
    { value: "BAMA", label: "BAHAMAS" },
    { value: "BAHR", label: "BAHRAIN" },
    { value: "BANG", label: "BANGLADESH" },
    { value: "BRDO", label: "BARBADOS" },
    { value: "BYS", label: "BELARUS" },
    { value: "BELG", label: "BELGIUM" },
    { value: "BLZ", label: "BELIZE" },
    { value: "BENN", label: "BENIN" },
    { value: "BERM", label: "BERMUDA" },
    { value: "BHU", label: "BHUTAN" },
    { value: "BOL", label: "BOLIVIA" },
    { value: "BIH", label: "BOSNIA-HERZEGOVINA" },
    { value: "BOT", label: "BOTSWANA" },
    { value: "BRNI", label: "BRUNEI" },
    { value: "BULG", label: "BULGARIA" },
    { value: "BURK", label: "BURKINA FASO" },
    { value: "BURM", label: "BURMA" },
    { value: "BRND", label: "BURUNDI" },
    { value: "CBDA", label: "CAMBODIA" },
    { value: "CMRN", label: "CAMEROON" },
    { value: "CAN", label: "CANADA" },
    { value: "CAVI", label: "CABO VERDE" },
    { value: "CAYI", label: "CAYMAN ISLANDS" },
    { value: "CAFR", label: "CENTRAL AFRICAN REPUBLIC" },
    { value: "CHAD", label: "CHAD" },
    { value: "CHIL", label: "CHILE" },
    { value: "CHIN", label: "CHINA" },
    { value: "COL", label: "COLOMBIA" },
    { value: "COMO", label: "COMOROS" },
    { value: "COD", label: "CONGO, DEMOCRATIC REPUBLIC OF THE" },
    { value: "CONB", label: "CONGO, REPUBLIC OF THE" },
    { value: "CSTR", label: "COSTA RICA" },
    { value: "IVCO", label: "COTE D\`IVOIRE" },
    { value: "HRV", label: "CROATIA" },
    { value: "CUBA", label: "CUBA" },
    { value: "CYPR", label: "CYPRUS" },
    { value: "CZEC", label: "CZECH REPUBLIC" },
    { value: "DEN", label: "DENMARK" },
    { value: "DJI", label: "DJIBOUTI" },
    { value: "DOMN", label: "DOMINICA" },
    { value: "DOMR", label: "DOMINICAN REPUBLIC" },
    { value: "ECUA", label: "ECUADOR" },
    { value: "EGYP", label: "EGYPT" },
    { value: "ELSL", label: "EL SALVADOR" },
    { value: "EGN", label: "EQUATORIAL GUINEA" },
    { value: "ERI", label: "ERITREA" },
    { value: "EST", label: "ESTONIA" },
    { value: "SZLD", label: "ESWATINI" },
    { value: "ETH", label: "ETHIOPIA" },
    { value: "FIJI", label: "FIJI" },
    { value: "FIN", label: "FINLAND" },
    { value: "FRAN", label: "FRANCE" },
    { value: "GABN", label: "GABON" },
    { value: "GAM", label: "GAMBIA, THE" },
    { value: "GEO", label: "GEORGIA" },
    { value: "GER", label: "GERMANY" },
    { value: "GHAN", label: "GHANA" },
    { value: "GIB", label: "GIBRALTAR" },
    { value: "GRC", label: "GREECE" },
    { value: "GREN", label: "GRENADA" },
    { value: "GUAT", label: "GUATEMALA" },
    { value: "GNEA", label: "GUINEA" },
    { value: "GUIB", label: "GUINEA - BISSAU" },
    { value: "GUY", label: "GUYANA" },
    { value: "HAT", label: "HAITI" },
    { value: "VAT", label: "HOLY SEE (VATICAN CITY)" },
    { value: "HOND", label: "HONDURAS" },
    { value: "HOKO", label: "HONG KONG BNO" },
    { value: "HNK", label: "HONG KONG SAR" },
    { value: "HUNG", label: "HUNGARY" },
    { value: "ICLD", label: "ICELAND" },
    { value: "IND", label: "INDIA" },
    { value: "IDSA", label: "INDONESIA" },
    { value: "IRAN", label: "IRAN" },
    { value: "IRAQ", label: "IRAQ" },
    { value: "IRE", label: "IRELAND" },
    { value: "ISRL", label: "ISRAEL" },
    { value: "ITLY", label: "ITALY" },
    { value: "JAM", label: "JAMAICA" },
    { value: "JPN", label: "JAPAN" },
    { value: "JORD", label: "JORDAN" },
    { value: "KAZ", label: "KAZAKHSTAN" },
    { value: "KENY", label: "KENYA" },
    { value: "KIRI", label: "KIRIBATI" },
    { value: "PRK", label: "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)" },
    { value: "KOR", label: "KOREA, REPUBLIC OF (SOUTH)" },
    { value: "KSV", label: "KOSOVO" },
    { value: "KUWT", label: "KUWAIT" },
    { value: "KGZ", label: "KYRGYZSTAN" },
    { value: "LAOS", label: "LAOS" },
    { value: "LATV", label: "LATVIA" },
    { value: "LEBN", label: "LEBANON" },
    { value: "LES", label: "LESOTHO" },
    { value: "LIBR", label: "LIBERIA" },
    { value: "LBYA", label: "LIBYA" },
    { value: "LCHT", label: "LIECHTENSTEIN" },
    { value: "LITH", label: "LITHUANIA" },
    { value: "LXM", label: "LUXEMBOURG" },
    { value: "MAC", label: "MACAU" },
    { value: "MKD", label: "MACEDONIA, NORTH" },
    { value: "MADG", label: "MADAGASCAR" },
    { value: "MALW", label: "MALAWI" },
    { value: "MLAS", label: "MALAYSIA" },
    { value: "MLDV", label: "MALDIVES" },
    { value: "MALI", label: "MALI" },
    { value: "MLTA", label: "MALTA" },
    { value: "RMI", label: "MARSHALL ISLANDS" },
    { value: "MAUR", label: "MAURITANIA" },
    { value: "MRTS", label: "MAURITIUS" },
    { value: "MEX", label: "MEXICO" },
    { value: "FSM", label: "MICRONESIA" },
    { value: "MLD", label: "MOLDOVA" },
    { value: "MON", label: "MONACO" },
    { value: "MONG", label: "MONGOLIA" },
    { value: "MTG", label: "MONTENEGRO" },
    { value: "MONT", label: "MONTSERRAT" },
    { value: "MORO", label: "MOROCCO" },
    { value: "MOZ", label: "MOZAMBIQUE" },
    { value: "NAMB", label: "NAMIBIA" },
    { value: "NAU", label: "NAURU" },
    { value: "NEP", label: "NEPAL" },
    { value: "NETH", label: "NETHERLANDS" },
    { value: "NZLD", label: "NEW ZEALAND" },
    { value: "NIC", label: "NICARAGUA" },
    { value: "NIR", label: "NIGER" },
    { value: "NRA", label: "NIGERIA" },
    { value: "NORW", label: "NORWAY" },
    { value: "OMAN", label: "OMAN" },
    { value: "PKST", label: "PAKISTAN" },
    { value: "PALA", label: "PALAU" },
    { value: "PAL", label: "PALESTINIAN AUTHORITY" },
    { value: "PAN", label: "PANAMA" },
    { value: "PNG", label: "PAPUA NEW GUINEA" },
    { value: "PARA", label: "PARAGUAY" },
    { value: "PERU", label: "PERU" },
    { value: "PHIL", label: "PHILIPPINES" },
    { value: "PITC", label: "PITCAIRN ISLANDS" },
    { value: "POL", label: "POLAND" },
    { value: "PORT", label: "PORTUGAL" },
    { value: "QTAR", label: "QATAR" },
    { value: "ROM", label: "ROMANIA" },
    { value: "RUS", label: "RUSSIA" },
    { value: "RWND", label: "RWANDA" },
    { value: "WSAM", label: "SAMOA" },
    { value: "SMAR", label: "SAN MARINO" },
    { value: "STPR", label: "SAO TOME AND PRINCIPE" },
    { value: "SARB", label: "SAUDI ARABIA" },
    { value: "SENG", label: "SENEGAL" },
    { value: "SBA", label: "SERBIA" },
    { value: "SEYC", label: "SEYCHELLES" },
    { value: "SLEO", label: "SIERRA LEONE" },
    { value: "SING", label: "SINGAPORE" },
    { value: "SVK", label: "SLOVAKIA" },
    { value: "SVN", label: "SLOVENIA" },
    { value: "SLMN", label: "SOLOMON ISLANDS" },
    { value: "SOMA", label: "SOMALIA" },
    { value: "SAFR", label: "SOUTH AFRICA" },
    { value: "SSDN", label: "SOUTH SUDAN" },
    { value: "SPN", label: "SPAIN" },
    { value: "SRL", label: "SRI LANKA" },
    { value: "SHEL", label: "ST. HELENA" },
    { value: "STCN", label: "ST. KITTS AND NEVIS" },
    { value: "SLCA", label: "ST. LUCIA" },
    { value: "STVN", label: "ST. VINCENT AND THE GRENADINES" },
    { value: "XXX", label: "STATELESS" },
    { value: "SUDA", label: "SUDAN" },
    { value: "SURM", label: "SURINAME" },
    { value: "SWDN", label: "SWEDEN" },
    { value: "SWTZ", label: "SWITZERLAND" },
    { value: "SYR", label: "SYRIA" },
    { value: "TWAN", label: "TAIWAN" },
    { value: "TJK", label: "TAJIKISTAN" },
    { value: "TAZN", label: "TANZANIA" },
    { value: "THAI", label: "THAILAND" },
    { value: "TMOR", label: "TIMOR-LESTE" },
    { value: "TOGO", label: "TOGO" },
    { value: "TONG", label: "TONGA" },
    { value: "TRIN", label: "TRINIDAD AND TOBAGO" },
    { value: "TNSA", label: "TUNISIA" },
    { value: "TRKY", label: "TURKEY" },
    { value: "TKM", label: "TURKMENISTAN" },
    { value: "TCIS", label: "TURKS AND CAICOS ISLANDS" },
    { value: "TUV", label: "TUVALU" },
    { value: "UGAN", label: "UGANDA" },
    { value: "UKR", label: "UKRAINE" },
    { value: "UAE", label: "UNITED ARAB EMIRATES" },
    { value: "GRBR", label: "UNITED KINGDOM" },
    { value: "URU", label: "URUGUAY" },
    { value: "UZB", label: "UZBEKISTAN" },
    { value: "VANU", label: "VANUATU" },
    { value: "VENZ", label: "VENEZUELA" },
    { value: "VTNM", label: "VIETNAM" },
    { value: "BRVI", label: "VIRGIN ISLANDS, BRITISH" },
    { value: "WAFT", label: "WALLIS AND FUTUNA ISLANDS" },
    { value: "SSAH", label: "WESTERN SAHARA" },
    { value: "YEM", label: "YEMEN" },
    { value: "ZAMB", label: "ZAMBIA" },
    { value: "ZIMB", label: "ZIMBABWE" }
];

export const usStates = [
    { value: "AL", label: "Alabama" }, { value: "AK", label: "Alaska" }, { value: "AZ", label: "Arizona" }, { value: "AR", label: "Arkansas" },
    { value: "CA", label: "California" }, { value: "CO", label: "Colorado" }, { value: "CT", label: "Connecticut" }, { value: "DE", label: "Delaware" },
    { value: "FL", label: "Florida" }, { value: "GA", label: "Georgia" }, { value: "HI", label: "Hawaii" }, { value: "ID", label: "Idaho" },
    { value: "IL", label: "Illinois" }, { value: "IN", label: "Indiana" }, { value: "IA", label: "Iowa" }, { value: "KS", label: "Kansas" },
    { value: "KY", label: "Kentucky" }, { value: "LA", label: "Louisiana" }, { value: "ME", label: "Maine" }, { value: "MA", label: "Massachusetts" },
    { value: "MD", label: "Maryland" }, { value: "MI", label: "Michigan" }, { value: "MN", label: "Minnesota" },
    { value: "MS", label: "Mississippi" }, { value: "MO", label: "Missouri" }, { value: "MT", label: "Montana" },
    { value: "NE", label: "Nebraska" }, { value: "NV", label: "Nevada" }, { value: "NH", label: "New Hampshire" },
    { value: "NJ", label: "New Jersey" }, { value: "NM", label: "New Mexico" }, { value: "NY", label: "New York" },
    { value: "NC", label: "North Carolina" }, { value: "ND", label: "North Dakota" }, { value: "OH", label: "Ohio" },
    { value: "OK", label: "Oklahoma" }, { value: "OR", label: "Oregon" }, { value: "PA", label: "Pennsylvania" },
    { value: "RI", label: "Rhode Island" }, { value: "SC", label: "South Carolina" }, { value: "SD", label: "South Dakota" },
    { value: "TN", label: "Tennessee" }, { value: "TX", label: "Texas" }, { value: "UT", label: "Utah" }, { value: "VT", label: "Vermont" },
    { value: "VA", label: "Virginia" }, { value: "WA", label: "Washington" }, { value: "WV", label: "West Virginia" },
    { value: "WI", label: "Wisconsin" }, { value: "WY", label: "Wyoming" }, { value: "DC", label: "District of Columbia" }
];

export const relationships = [
    { value: "P", label: "Pai/Mãe" },
    { value: "S", label: "Cônjuge" },
    { value: "C", label: "Filho(a)" },
    { value: "R", label: "Outro Parente" },
    { value: "F", label: "Amigo(a)" },
    { value: "B", label: "Parceiro de Negócios" },
    { value: "O", label: "Outro" }
];

export const usContactRelationships = [
    { value: "R", label: "Parente" }, { value: "S", label: "Cônjuge" },
    { value: "C", label: "Amigo/Amiga" }, { value: "B", label: "Sócio/Sócia" },
    { value: "P", label: "Empregador" }, { value: "H", label: "Oficial de Escola" },
    { value: "O", label: "Outro" }
];

export const relativeTypes = [
    { value: "S", label: "Cônjuge" }, { value: "F", label: "Noivo(a)" },
    { value: "C", label: "Filho(a)" }, { value: "B", label: "Irmão/Irmã" }
];

export const usStatus = [
    { value: "S", label: "Cidadão americano" }, { value: "C", label: "Residente permanente (LPR)" },
    { value: "P", label: "Não-imigrante" }, { value: "O", label: "Outro / Não sei" }
];

export const occupations = [
    { value: "A", label: "Agricultura" }, { value: "AP", label: "Artista/Intérprete" }, { value: "B", label: "Negócios" },
    { value: "CM", label: "Comunicação" }, { value: "CS", label: "Ciência da Computação" }, { value: "C", label: "Culinária/Serviços Gastronômico" },
    { value: "ED", label: "Educação" }, { value: "EN", label: "Engenharia" }, { value: "G", label: "Governo" },
    { value: "H", label: "Do Lar" }, { value: "LP", label: "Profissão Legal" }, { value: "MH", label: "Médico/Saúde" },
    { value: "M", label: "Militar" }, { value: "NS", label: "Ciência Natural" }, { value: "N", label: "Desempregado" },
    { value: "PS", label: "Ciências Físicas" }, { value: "RV", label: "Vocação Religiosa" }, { value: "R", label: "Pesquisa" },
    { value: "RT", label: "Aposentado" }, { value: "SS", label: "Ciência Social" }, { value: "S", label: "Estudante" },
    { value: "O", label: "Outro" }
];

/**
 * All shared options as a single object (for schema aggregator compatibility)
 */
export const allOptions = {
    countries,
    usStates,
    relationships,
    usContactRelationships,
    relativeTypes,
    usStatus,
    occupations
};
