/** 01-location — Local da Entrevista */
export default {
    id: "location",
    label: "Local da Entrevista",
    fields: [
        {
            id: "location", label: "Selecione o local onde você solicitará este visto.", type: "select", required: true, ds160: "ddlLocation", options: [
                // ── Brasil (topo) ──
                { value: "BRA", label: "BRAZIL, BRASILIA" },
                { value: "PTA", label: "BRAZIL, PORTO ALEGRE" },
                { value: "RCF", label: "BRAZIL, RECIFE" },
                { value: "RDJ", label: "BRAZIL, RIO DE JANEIRO" },
                { value: "SPL", label: "BRAZIL, SAO PAULO" },
                // Divisor
                { value: "", label: "────────────────────", disabled: true },
                // ── Demais locais (ordem oficial) ──
                { value: "TIA", label: "ALBANIA, TIRANA" },
                { value: "ALG", label: "ALGERIA, ALGIERS" },
                { value: "LUA", label: "ANGOLA, LUANDA" },
                { value: "BNS", label: "ARGENTINA, BUENOS AIRES" },
                { value: "YRV", label: "ARMENIA, YEREVAN" },
                { value: "MLB", label: "AUSTRALIA, MELBOURNE" },
                { value: "PRT", label: "AUSTRALIA, PERTH" },
                { value: "SYD", label: "AUSTRALIA, SYDNEY" },
                { value: "VNN", label: "AUSTRIA, VIENNA" },
                { value: "BKU", label: "AZERBAIJAN, BAKU" },
                { value: "NSS", label: "BAHAMAS, NASSAU" },
                { value: "MNA", label: "BAHRAIN, MANAMA" },
                { value: "DHK", label: "BANGLADESH, DHAKA" },
                { value: "BGN", label: "BARBADOS, BRIDGETOWN" },
                { value: "BRS", label: "BELGIUM, BRUSSELS" },
                { value: "BLZ", label: "BELIZE, BELMOPAN" },
                { value: "COT", label: "BENIN, COTONOU" },
                { value: "HML", label: "BERMUDA, HAMILTON" },
                { value: "LPZ", label: "BOLIVIA, LA PAZ" },
                { value: "SAR", label: "BOSNIA-HERZEGOVINA, SARAJEVO" },
                { value: "GAB", label: "BOTSWANA, GABORONE" },
                { value: "BSB", label: "BRUNEI, BANDAR SERI BEGAWAN" },
                { value: "SOF", label: "BULGARIA, SOFIA" },
                { value: "OUG", label: "BURKINA FASO, OUAGADOUGOU" },
                { value: "RNG", label: "BURMA, RANGOON" },
                { value: "BUJ", label: "BURUNDI, BUJUMBURA" },
                { value: "PIA", label: "CABO VERDE, PRAIA" },
                { value: "PHP", label: "CAMBODIA, PHNOM PENH" },
                { value: "YDE", label: "CAMEROON, YAOUNDE" },
                { value: "CLG", label: "CANADA, CALGARY" },
                { value: "HLF", label: "CANADA, HALIFAX" },
                { value: "MTL", label: "CANADA, MONTREAL" },
                { value: "OTT", label: "CANADA, OTTAWA" },
                { value: "QBC", label: "CANADA, QUEBEC" },
                { value: "TRT", label: "CANADA, TORONTO" },
                { value: "VAC", label: "CANADA, VANCOUVER" },
                { value: "NDJ", label: "CHAD, N'DJAMENA" },
                { value: "SNT", label: "CHILE, SANTIAGO" },
                { value: "BEJ", label: "CHINA, BEIJING" },
                { value: "GUZ", label: "CHINA, GUANGZHOU" },
                { value: "SHG", label: "CHINA, SHANGHAI" },
                { value: "SNY", label: "CHINA, SHENYANG" },
                { value: "WUH", label: "CHINA, WUHAN" },
                { value: "BGT", label: "COLOMBIA, BOGOTA" },
                { value: "BRZ", label: "CONGO, BRAZZAVILLE" },
                { value: "KIN", label: "CONGO, KINSHASA" },
                { value: "SNJ", label: "COSTA RICA, SAN JOSE" },
                { value: "ABJ", label: "COTE D'IVORIE, ABIDJAN" },
                { value: "ZGB", label: "CROATIA, ZAGREB" },
                { value: "HAV", label: "CUBA, HAVANA" },
                { value: "CRC", label: "CURACAO, CURACAO" },
                { value: "NCS", label: "CYPRUS, NICOSIA" },
                { value: "PRG", label: "CZECH REPUBLIC, PRAGUE" },
                { value: "CPN", label: "DENMARK, COPENHAGEN" },
                { value: "DJI", label: "DJIBOUTI, DJIBOUTI" },
                { value: "SDO", label: "DOMINICAN REPUBLIC, SANTO DOMINGO" },
                { value: "GYQ", label: "ECUADOR, GUAYAQUIL" },
                { value: "QTO", label: "ECUADOR, QUITO" },
                { value: "CRO", label: "EGYPT, CAIRO" },
                { value: "SNS", label: "EL SALVADOR, SAN SALVADOR" },
                { value: "LND", label: "ENGLAND, LONDON" },
                { value: "MBO", label: "EQUATORIAL GUINEA, MALABO" },
                { value: "ASM", label: "ERITREA, ASMARA" },
                { value: "TAL", label: "ESTONIA, TALLINN" },
                { value: "MBA", label: "ESWATINI, MBABANE" },
                { value: "ADD", label: "ETHIOPIA, ADDIS ABABA" },
                { value: "SUV", label: "FIJI, SUVA" },
                { value: "HLS", label: "FINLAND, HELSINKI" },
                { value: "PRS", label: "FRANCE, PARIS" },
                { value: "LIB", label: "GABON, LIBREVILLE" },
                { value: "BAN", label: "GAMBIA, BANJUL" },
                { value: "TBL", label: "GEORGIA, TBILISI" },
                { value: "BRL", label: "GERMANY, BERLIN" },
                { value: "FRN", label: "GERMANY, FRANKFURT" },
                { value: "MUN", label: "GERMANY, MUNICH" },
                { value: "ACC", label: "GHANA, ACCRA" },
                { value: "ATH", label: "GREECE, ATHENS" },
                { value: "GTM", label: "GUATEMALA, GUATEMALA CITY" },
                { value: "CRY", label: "GUINEA, CONAKRY" },
                { value: "GEO", label: "GUYANA, GEORGETOWN" },
                { value: "PTP", label: "HAITI, PORT-AU-PRINCE" },
                { value: "TGG", label: "HONDURAS, TEGUCIGALPA" },
                { value: "HNK", label: "HONG KONG" },
                { value: "BDP", label: "HUNGARY, BUDAPEST" },
                { value: "RKJ", label: "ICELAND, REYKJAVIK" },
                { value: "MDR", label: "INDIA, CHENNAI" },
                { value: "HYD", label: "INDIA, HYDERABAD" },
                { value: "CLC", label: "INDIA, KOLKATA" },
                { value: "BMB", label: "INDIA, MUMBAI" },
                { value: "NWD", label: "INDIA, NEW DELHI" },
                { value: "JAK", label: "INDONESIA, JAKARTA" },
                { value: "SRB", label: "INDONESIA, SURABAYA" },
                { value: "BGH", label: "IRAQ, BAGHDAD" },
                { value: "ERB", label: "IRAQ, ERBIL" },
                { value: "DBL", label: "IRELAND, DUBLIN" },
                { value: "TLV", label: "ISRAEL, TEL AVIV" },
                { value: "FLR", label: "ITALY, FLORENCE" },
                { value: "MLN", label: "ITALY, MILAN" },
                { value: "NPL", label: "ITALY, NAPLES" },
                { value: "RME", label: "ITALY, ROME" },
                { value: "KNG", label: "JAMAICA, KINGSTON" },
                { value: "NHA", label: "JAPAN, NAHA" },
                { value: "KBO", label: "JAPAN, OSAKA/FUKUOKA" },
                { value: "TKY", label: "JAPAN, TOKYO/SAPPORO" },
                { value: "JRS", label: "JERUSALEM" },
                { value: "AMM", label: "JORDAN, AMMAN" },
                { value: "ATA", label: "KAZAKHSTAN, ALMATY" },
                { value: "AST", label: "KAZAKHSTAN, ASTANA" },
                { value: "NRB", label: "KENYA, NAIROBI" },
                { value: "PRI", label: "KOSOVO, PRISTINA" },
                { value: "KWT", label: "KUWAIT, KUWAIT CITY" },
                { value: "BKK", label: "KYRGYZSTAN, BISHKEK" },
                { value: "VNT", label: "LAOS, VIENTIANE" },
                { value: "RGA", label: "LATVIA, RIGA" },
                { value: "BRT", label: "LEBANON, BEIRUT" },
                { value: "MAS", label: "LESOTHO, MASERU" },
                { value: "MRV", label: "LIBERIA, MONROVIA" },
                { value: "VIL", label: "LITHUANIA, VILNIUS" },
                { value: "LXM", label: "LUXEMBOURG, LUXEMBOURG" },
                { value: "ANT", label: "MADAGASCAR, ANTANANARIVO" },
                { value: "LIL", label: "MALAWI, LILONGWE" },
                { value: "KLL", label: "MALAYSIA, KUALA LUMPUR" },
                { value: "BAM", label: "MALI, BAMAKO" },
                { value: "VLL", label: "MALTA, VALLETTA" },
                { value: "MAJ", label: "MARSHALL ISLANDS, MAJURO" },
                { value: "NUK", label: "MAURITANIA, NOUAKCHOTT" },
                { value: "PTL", label: "MAURITIUS, PORT LOUIS" },
                { value: "CDJ", label: "MEXICO, CIUDAD JUAREZ" },
                { value: "GDL", label: "MEXICO, GUADALAJARA" },
                { value: "HER", label: "MEXICO, HERMOSILLO" },
                { value: "MTM", label: "MEXICO, MATAMOROS" },
                { value: "MER", label: "MEXICO, MERIDA" },
                { value: "MEX", label: "MEXICO, MEXICO CITY" },
                { value: "MTR", label: "MEXICO, MONTERREY" },
                { value: "NGL", label: "MEXICO, NOGALES" },
                { value: "NVL", label: "MEXICO, NUEVO LAREDO" },
                { value: "TJT", label: "MEXICO, TIJUANA" },
                { value: "KOL", label: "MICRONESIA, KOLONIA" },
                { value: "CHS", label: "MOLDOVA, CHISINAU" },
                { value: "ULN", label: "MONGOLIA, ULAANBAATAR" },
                { value: "POD", label: "MONTENEGRO, PODGORICA" },
                { value: "CSB", label: "MOROCCO, CASABLANCA" },
                { value: "MAP", label: "MOZAMBIQUE, MAPUTO" },
                { value: "WHK", label: "NAMIBIA, WINDHOEK" },
                { value: "KDU", label: "NEPAL, KATHMANDU" },
                { value: "AMS", label: "NETHERLANDS, AMSTERDAM" },
                { value: "ACK", label: "NEW ZEALAND, AUCKLAND" },
                { value: "MNG", label: "NICARAGUA, MANAGUA" },
                { value: "NMY", label: "NIGER, NIAMEY" },
                { value: "ABU", label: "NIGERIA, ABUJA" },
                { value: "LGS", label: "NIGERIA, LAGOS" },
                { value: "SKO", label: "NORTH MACEDONIA, SKOPJE" },
                { value: "BLF", label: "NORTHERN IRELAND, BELFAST" },
                { value: "OSL", label: "NORWAY, OSLO" },
                { value: "MST", label: "OMAN, MUSCAT" },
                { value: "ISL", label: "PAKISTAN, ISLAMABAD" },
                { value: "KRC", label: "PAKISTAN, KARACHI" },
                { value: "KOR", label: "PALAU, KOROR" },
                { value: "PNM", label: "PANAMA, PANAMA CITY" },
                { value: "PTM", label: "PAPUA NEW GUINEA, PORT MORESBY" },
                { value: "ASN", label: "PARAGUAY, ASUNCION" },
                { value: "LMA", label: "PERU, LIMA" },
                { value: "MNL", label: "PHILIPPINES, MANILA" },
                { value: "KRK", label: "POLAND, KRAKOW" },
                { value: "WRW", label: "POLAND, WARSAW" },
                { value: "LSB", label: "PORTUGAL, LISBON" },
                { value: "DOH", label: "QATAR, DOHA" },
                { value: "BCH", label: "ROMANIA, BUCHAREST" },
                { value: "MOS", label: "RUSSIA, MOSCOW" },
                { value: "KGL", label: "RWANDA, KIGALI" },
                { value: "APA", label: "SAMOA, APIA" },
                { value: "DHR", label: "SAUDI ARABIA, DHAHRAN" },
                { value: "JDD", label: "SAUDI ARABIA, JEDDAH" },
                { value: "RID", label: "SAUDI ARABIA, RIYADH" },
                { value: "DKR", label: "SENEGAL, DAKAR" },
                { value: "BLG", label: "SERBIA, BELGRADE" },
                { value: "FTN", label: "SIERRA LEONE, FREETOWN" },
                { value: "SGP", label: "SINGAPORE, SINGAPORE" },
                { value: "BTS", label: "SLOVAKIA, BRATISLAVA" },
                { value: "LJU", label: "SLOVENIA, LJUBLJANA" },
                { value: "CPT", label: "SOUTH AFRICA, CAPE TOWN" },
                { value: "DRB", label: "SOUTH AFRICA, DURBAN" },
                { value: "JHN", label: "SOUTH AFRICA, JOHANNESBURG" },
                { value: "SEO", label: "SOUTH KOREA, SEOUL" },
                { value: "JBA", label: "SOUTH SUDAN, JUBA" },
                { value: "MDD", label: "SPAIN, MADRID" },
                { value: "CLM", label: "SRI LANKA, COLOMBO" },
                { value: "PRM", label: "SURINAME, PARAMARIBO" },
                { value: "STK", label: "SWEDEN, STOCKHOLM" },
                { value: "BEN", label: "SWITZERLAND, BERN" },
                { value: "TAI", label: "TAIWAN, TAIPEI" },
                { value: "DHB", label: "TAJIKISTAN, DUSHANBE" },
                { value: "DRS", label: "TANZANIA, DAR ES SALAAM" },
                { value: "BNK", label: "THAILAND, BANGKOK" },
                { value: "CHN", label: "THAILAND, CHIANG MAI" },
                { value: "DIL", label: "TIMOR LESTE, DILI" },
                { value: "LOM", label: "TOGO, LOME" },
                { value: "PTS", label: "TRINIDAD, PORT OF SPAIN" },
                { value: "TNS", label: "TUNISIA, TUNIS" },
                { value: "ANK", label: "TURKEY, ANKARA" },
                { value: "IST", label: "TURKEY, ISTANBUL" },
                { value: "AKD", label: "TURKMENISTAN, ASHGABAT" },
                { value: "KMP", label: "UGANDA, KAMPALA" },
                { value: "KEV", label: "UKRAINE, KYIV" },
                { value: "ABD", label: "UNITED ARAB EMIRATES, ABU DHABI" },
                { value: "DUB", label: "UNITED ARAB EMIRATES, DUBAI" },
                { value: "MTV", label: "URUGUAY, MONTEVIDEO" },
                { value: "THT", label: "UZBEKISTAN, TASHKENT" },
                { value: "HAN", label: "VIETNAM, HANOI" },
                { value: "HCM", label: "VIETNAM, HO CHI MINH CITY" },
                { value: "LUS", label: "ZAMBIA, LUSAKA" },
                { value: "HRE", label: "ZIMBABWE, HARARE" }
            ]
        },
        {
            id: "locationPhotoWarning", type: "alert", alertStyle: "warning",
            label: "Para essa localidade exigirá que você carregue uma foto digital sua antes, um de nossos assessores vai falar com você em um segundo momento.",
            showWhen: { field: "location", in: ["PTA", "RCF"] }
        }
    ]
};
